language: node_js
node_js:
  - "4"
  - "5"
services:
  - mongodb
before_build:
  - npm version 0.1.$TRAVIS_BUILD_NUMBER
deploy:
  provider: npm
  email: "dejan@fajfar.com"
  api_key: "$npm_key"
  on:
    branch: master