language: node_js
node_js:
  - "8"
  - "10"
services:
  - mongodb
before_install:
  - git config --global user.email "you@example.com"
  - git config --global user.name "travisbuild"
before_script:
  - npm version 0.9.2
deploy:
  provider: npm
  email: "dejan@fajfar.com"
  api_key: "$npm_key"
  on: release