language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "4"
  - "5.0"
  - "5.4"
  - "5"
services:
  - mongodb
before_install:
  - git config --global user.email "you@example.com"
  - git config --global user.name "travisbuild"
before_script:
  - npm version 0.2.$TRAVIS_BUILD_NUMBER
deploy:
  provider: npm
  email: "dejan@fajfar.com"
  api_key: "$npm_key"
  on: release